SUL_REGION = "SUL"
MEIO_OESTE_E_SERRA_CATARIENSE_REGION = "MEIO OESTE E SERRA CATARIENSE"
GRANDE_FLORIANOPOLIS_REGION = "GRANDE FLORIANOPOLIS"
ALTO_VALE_DO_ITAJAI_REGION = "ALTO VALE DO ITAJAI"
FOZ_DO_RIO_ITAJAI_REGION = "FOZ DO RIO ITAJAI"
GRANDE_OESTE_REGION = "GRANDE OESTE"
PLANALTO_NORTE_E_NORDESTE_REGION = "PLANALTO NORTE E NORDESTE"
SUL_REGION_NEIGHBORS = ["MEIO OESTE E SERRA CATARIENSE", "GRANDE FLORIANOPOLIS"]
MEIO_OESTE_E_SERRA_CATARIENSE_REGION_NEIGHBORS = ["GRANDE OESTE", "PLANALTO NORTE E NORDESTE", "ALTO VALE DO ITAJAI", "GRANDE FLORIANOPOLIS", "SUL"]
GRANDE_FLORIANOPOLIS_REGION_NEIGHBORS = ["SUL", "MEIO OESTE E SERRA CATARIENSE", "ALTO VALE DO ITAJAI", "FOZ DO RIO ITAJAI"]
ALTO_VALE_DO_ITAJAI_REGION_NEIGHBORS = ["GRANDE FLORIANOPOLIS", "FOZ DO RIO ITAJAI", "MEIO OESTE E SERRA CATARIENSE", "PLANALTO NORTE E NORDESTE"]
FOZ_DO_RIO_ITAJAI_REGION_NEIGHBORS = ["ALTO VALE DO ITAJAI", "PLANALTO NORTE E NORDESTE", "GRANDE FLORIANOPOLIS"]
GRANDE_OESTE_REGION_NEIGHBORS = ["MEIO OESTE E SERRA CATARIENSE"]
PLANALTO_NORTE_E_NORDESTE_REGION_NEIGHBORS = ["ALTO VALE DO ITAJAI", "FOZ DO RIO ITAJAI", "GRANDE FLORIANOPOLIS", "MEIO OESTE E SERRA CATARIENSE"]

REGIONS_SEQ_AND_ITS_NEIGHBORS = ["SUL", "MEIO OESTE E SERRA CATARIENSE", "GRANDE FLORIANOPOLIS", "ALTO VALE DO ITAJAI", "FOZ DO RIO ITAJAI", "GRANDE OESTE", "PLANALTO NORTE E NORDESTE", 
"MEIO OESTE E SERRA CATARIENSE", "GRANDE FLORIANOPOLIS", #7, 8
"GRANDE OESTE", "PLANALTO NORTE E NORDESTE", "ALTO VALE DO ITAJAI", "GRANDE FLORIANOPOLIS", "SUL", #9, 10, 11, 12, 13
"SUL", "MEIO OESTE E SERRA CATARIENSE", "ALTO VALE DO ITAJAI", "FOZ DO RIO ITAJAI", #14, 15, 16, 17
"GRANDE FLORIANOPOLIS", "FOZ DO RIO ITAJAI", "MEIO OESTE E SERRA CATARIENSE", "PLANALTO NORTE E NORDESTE", #18, 19, 20, 21
"ALTO VALE DO ITAJAI", "PLANALTO NORTE E NORDESTE", "GRANDE FLORIANOPOLIS", #22, 23, 24
"MEIO OESTE E SERRA CATARIENSE", #25
"ALTO VALE DO ITAJAI", "FOZ DO RIO ITAJAI", "GRANDE FLORIANOPOLIS", "MEIO OESTE E SERRA CATARIENSE"] #26, 27, 28, 29