SUL_REGION = "SUL"
MEIO_OESTE_E_SERRA_CATARIENSE_REGION = "MEIO OESTE E SERRA CATARINENSE"
GRANDE_FLORIANOPOLIS_REGION = "GRANDE FLORIANOPOLIS"
ALTO_VALE_DO_ITAJAI_REGION = "ALTO VALE DO ITAJAI"
FOZ_DO_RIO_ITAJAI_REGION = "FOZ DO RIO ITAJAI"
GRANDE_OESTE_REGION = "GRANDE OESTE"
PLANALTO_NORTE_E_NORDESTE_REGION = "PLANALTO NORTE E NORDESTE"
SUL_REGION_NEIGHBORS = ["MEIO OESTE E SERRA CATARINENSE", "GRANDE FLORIANOPOLIS"]
MEIO_OESTE_E_SERRA_CATARIENSE_REGION_NEIGHBORS = ["GRANDE OESTE", "PLANALTO NORTE E NORDESTE", "ALTO VALE DO ITAJAI", "GRANDE FLORIANOPOLIS", "SUL"]
GRANDE_FLORIANOPOLIS_REGION_NEIGHBORS = ["SUL", "MEIO OESTE E SERRA CATARINENSE", "ALTO VALE DO ITAJAI", "FOZ DO RIO ITAJAI"]
ALTO_VALE_DO_ITAJAI_REGION_NEIGHBORS = ["GRANDE FLORIANOPOLIS", "FOZ DO RIO ITAJAI", "MEIO OESTE E SERRA CATARINENSE", "PLANALTO NORTE E NORDESTE"]
FOZ_DO_RIO_ITAJAI_REGION_NEIGHBORS = ["ALTO VALE DO ITAJAI", "PLANALTO NORTE E NORDESTE", "GRANDE FLORIANOPOLIS"]
GRANDE_OESTE_REGION_NEIGHBORS = ["MEIO OESTE E SERRA CATARINENSE"]
PLANALTO_NORTE_E_NORDESTE_REGION_NEIGHBORS = ["ALTO VALE DO ITAJAI", "FOZ DO RIO ITAJAI", "GRANDE FLORIANOPOLIS", "MEIO OESTE E SERRA CATARINENSE"]

REGIONS_SEQ_AND_ITS_NEIGHBORS = ["SUL", "MEIO OESTE E SERRA CATARINENSE", "GRANDE FLORIANOPOLIS", "ALTO VALE DO ITAJAI", "FOZ DO RIO ITAJAI", "GRANDE OESTE", "PLANALTO NORTE E NORDESTE", 
"MEIO OESTE E SERRA CATARINENSE", "GRANDE FLORIANOPOLIS", #7, 8
"GRANDE OESTE", "PLANALTO NORTE E NORDESTE", "ALTO VALE DO ITAJAI", "GRANDE FLORIANOPOLIS", "SUL", #9, 10, 11, 12, 13
"SUL", "MEIO OESTE E SERRA CATARINENSE", "ALTO VALE DO ITAJAI", "FOZ DO RIO ITAJAI", #14, 15, 16, 17
"GRANDE FLORIANOPOLIS", "FOZ DO RIO ITAJAI", "MEIO OESTE E SERRA CATARINENSE", "PLANALTO NORTE E NORDESTE", #18, 19, 20, 21
"ALTO VALE DO ITAJAI", "PLANALTO NORTE E NORDESTE", "GRANDE FLORIANOPOLIS", #22, 23, 24
"MEIO OESTE E SERRA CATARINENSE", #25
"ALTO VALE DO ITAJAI", "FOZ DO RIO ITAJAI", "GRANDE FLORIANOPOLIS", "MEIO OESTE E SERRA CATARINENSE"] #26, 27, 28, 29

REGIONS_INDEX = [SUL_REGION, MEIO_OESTE_E_SERRA_CATARIENSE_REGION, GRANDE_FLORIANOPOLIS_REGION, ALTO_VALE_DO_ITAJAI_REGION, 
                 FOZ_DO_RIO_ITAJAI_REGION, GRANDE_OESTE_REGION, PLANALTO_NORTE_E_NORDESTE_REGION]

REGIONS_AND_NEIGHBORS_DICT = {
    SUL_REGION: SUL_REGION_NEIGHBORS,
    MEIO_OESTE_E_SERRA_CATARIENSE_REGION: MEIO_OESTE_E_SERRA_CATARIENSE_REGION_NEIGHBORS,
    GRANDE_FLORIANOPOLIS_REGION: GRANDE_FLORIANOPOLIS_REGION_NEIGHBORS,
    ALTO_VALE_DO_ITAJAI_REGION: ALTO_VALE_DO_ITAJAI_REGION_NEIGHBORS,
    FOZ_DO_RIO_ITAJAI_REGION: FOZ_DO_RIO_ITAJAI_REGION_NEIGHBORS,
    GRANDE_OESTE_REGION: GRANDE_OESTE_REGION_NEIGHBORS,
    PLANALTO_NORTE_E_NORDESTE_REGION: PLANALTO_NORTE_E_NORDESTE_REGION_NEIGHBORS
}